### ISSUE TITLE
关于templates里的episode1.html

### ISSUE THREAD

**Issue by sq123-456** [idlerJiang/shanghaimemory#1]
里面存在大量乱码，***需要改正***

**Comment by idlerJiang** [comment]
请以episode2为模板复制出另外7个html，template里其余的7个html内容均已过时（包括但不限于引用未更新、超链接未正确设置、大量冗余代码等）
注意以ep2为模板替换时需要替换：109行（视频源）、118行（标题）、120行（简介）

**Comment by sq123-456** [comment]
完成
